import type { MenuItem } from '@/types/pos';

export const BREWED_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'cold_brew',
    categoryId: 'brewed',
    name: 'Cold Brew',
    isSubcategory: true,
    row: 1,
    col: 1,
  },
  {
    id: 'nitro',
    categoryId: 'brewed',
    name: 'Nitro',
    baseName: 'Nitro',
    hasSizes: true,
    price: 85000,
    prices: { S: 80000, T: 85000, G: 95000, V: 105000 },
    row: 1,
    col: 2,
  },
  {
    id: 'colombia',
    categoryId: 'brewed',
    name: 'COLOMBIA',
    baseName: 'COLOMBIA',
    hasSizes: false,
    price: 55000,
    row: 1,
    col: 3,
  },
  {
    id: 'french_roast',
    categoryId: 'brewed',
    name: 'FRENCH ROAST',
    baseName: 'FRENCH ROAST',
    hasSizes: false,
    price: 55000,
    row: 1,
    col: 4,
  },
  {
    id: 'espresso_brewed',
    categoryId: 'brewed',
    name: 'ESPRESSO',
    baseName: 'ESPRESSO',
    hasSizes: false,
    price: 55000,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'ethiopia',
    categoryId: 'brewed',
    name: 'ETHIOPIA',
    baseName: 'ETHIOPIA',
    hasSizes: false,
    price: 55000,
    row: 2,
    col: 1,
  },
  {
    id: 'guatamela',
    categoryId: 'brewed',
    name: 'GUATAMELA',
    baseName: 'GUATAMELA',
    hasSizes: false,
    price: 55000,
    row: 2,
    col: 2,
  },
  {
    id: 'house',
    categoryId: 'brewed',
    name: 'HOUSE',
    baseName: 'HOUSE',
    hasSizes: false,
    price: 55000,
    row: 2,
    col: 3,
  },
  {
    id: 'italian',
    categoryId: 'brewed',
    name: 'ITALIAN',
    baseName: 'ITALIAN',
    hasSizes: false,
    price: 55000,
    row: 2,
    col: 4,
  },
  {
    id: 'kenya',
    categoryId: 'brewed',
    name: 'KENYA',
    baseName: 'KENYA',
    hasSizes: false,
    price: 55000,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'pike_place',
    categoryId: 'brewed',
    name: 'PIKE PLACE',
    baseName: 'PIKE PLACE',
    hasSizes: false,
    price: 55000,
    row: 3,
    col: 1,
  },
  {
    id: 'sumatra',
    categoryId: 'brewed',
    name: 'SUMATRA',
    baseName: 'SUMATRA',
    hasSizes: false,
    price: 55000,
    row: 3,
    col: 2,
  },
  {
    id: 'verona',
    categoryId: 'brewed',
    name: 'VERONA',
    baseName: 'VERONA',
    hasSizes: false,
    price: 55000,
    row: 3,
    col: 3,
  },
  {
    id: 'veranda',
    categoryId: 'brewed',
    name: 'VERANDA',
    baseName: 'VERANDA',
    hasSizes: false,
    price: 55000,
    row: 3,
    col: 4,
  },
  {
    id: 'willow',
    categoryId: 'brewed',
    name: 'WILLOW',
    baseName: 'WILLOW',
    hasSizes: false,
    price: 55000,
    row: 3,
    col: 5,
  },

  // Row 4
  {
    id: 'siren_blend',
    categoryId: 'brewed',
    name: 'Siren Blend',
    baseName: 'Siren Blend',
    hasSizes: false,
    price: 55000,
    row: 4,
    col: 1,
  },
  {
    id: 'son_chau_blend',
    categoryId: 'brewed',
    name: 'Son Chau Blend',
    baseName: 'Son Chau Blend',
    hasSizes: false,
    price: 55000,
    row: 4,
    col: 2,
  },
  {
    id: 's_poc',
    categoryId: 'brewed',
    name: 'S POC',
    baseName: 'POC',
    hasSizes: true,
    price: 55000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 4,
    col: 3,
  },
  {
    id: 't_poc',
    categoryId: 'brewed',
    name: 'T POC',
    baseName: 'POC',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 4,
    col: 4,
  },
  {
    id: 't_iced_poc',
    categoryId: 'brewed',
    name: 'T Iced POC',
    baseName: 'Iced POC',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 4,
    col: 5,
  },

  // Row 5
  {
    id: 'voyage_blend',
    categoryId: 'brewed',
    name: 'Voyage Blend',
    baseName: 'Voyage Blend',
    hasSizes: false,
    price: 55000,
    row: 5,
    col: 1,
  },
  {
    id: 'sejati_blend',
    categoryId: 'brewed',
    name: 'Sejati Blend',
    baseName: 'Sejati Blend',
    hasSizes: false,
    price: 55000,
    row: 5,
    col: 2,
  },
  {
    id: 'autumn_blend',
    categoryId: 'brewed',
    name: 'Autumn Blend',
    baseName: 'Autumn Blend',
    hasSizes: false,
    price: 55000,
    row: 5,
    col: 3,
  },
  {
    id: 'dark_roast_1971',
    categoryId: 'brewed',
    name: '1971 Dark Roast',
    baseName: '1971 Dark Roast',
    hasSizes: false,
    price: 55000,
    row: 5,
    col: 4,
  },
];
