import type { MenuItem } from '@/types/pos';

// Top-level Food HN HY BNI menu
export const FOOD_ITEMS: MenuItem[] = [
  {
    id: 'food_bakery_hn',
    categoryId: 'food',
    name: 'BAKERY HN',
    isSubcategory: true,
    row: 1,
    col: 1,
  },
  {
    id: 'food_desserts_hn',
    categoryId: 'food',
    name: 'DESSERTS HN',
    isSubcategory: true,
    row: 1,
    col: 2,
  },
  {
    id: 'food_sandwiches_hn',
    categoryId: 'food',
    name: 'SANDWICHES HN',
    isSubcategory: true,
    row: 1,
    col: 3,
  },
  {
    id: 'food_snack_mixology_hn',
    categoryId: 'food',
    name: 'Snack Mixology HN',
    isSubcategory: true,
    row: 1,
    col: 4,
  },
];

// Subcategory: BAKERY HN
export const FOOD_BAKERY_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'mon_chocolate_donut',
    categoryId: 'food',
    name: 'Mon Chocolate Donut',
    hasSizes: false,
    price: 40000,
    stock: 2,
    row: 1,
    col: 1,
  },
  {
    id: 'butter_croissant_fz',
    categoryId: 'food',
    name: 'Butter Croissant FZ',
    hasSizes: false,
    price: 45000,
    stock: 6,
    row: 1,
    col: 2,
  },
  {
    id: 'chocolate_croissant',
    categoryId: 'food',
    name: 'Chocolate Croissant',
    hasSizes: false,
    price: 50000,
    stock: 3,
    row: 1,
    col: 3,
  },
  {
    id: 'mini_donuts',
    categoryId: 'food',
    name: 'Mini Donuts',
    hasSizes: false,
    price: 45000,
    stock: 2,
    row: 1,
    col: 4,
  },
  {
    id: 'apple_strudel',
    categoryId: 'food',
    name: 'Apple Strudel',
    hasSizes: false,
    price: 50000,
    stock: 5,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'banana_chocolate_muf',
    categoryId: 'food',
    name: 'Banana Chocolate Muf',
    hasSizes: false,
    price: 45000,
    stock: 3,
    row: 2,
    col: 1,
  },
  {
    id: 'skinny_blueberry_muf',
    categoryId: 'food',
    name: 'Skinny Blueberry Muf',
    hasSizes: false,
    price: 45000,
    stock: 2,
    row: 2,
    col: 2,
  },
  {
    id: 'pistachio_croissant',
    categoryId: 'food',
    name: 'Pistachio Croissant',
    hasSizes: false,
    price: 55000,
    stock: 1,
    row: 2,
    col: 3,
  },
  {
    id: 'banana_loaf',
    categoryId: 'food',
    name: 'Banana Loaf',
    hasSizes: false,
    price: 40000,
    stock: 2,
    row: 2,
    col: 4,
  },
  {
    id: 'apple_turnover',
    categoryId: 'food',
    name: 'Apple Turnover',
    hasSizes: false,
    price: 50000,
    stock: 1,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'matcha_croissant',
    categoryId: 'food',
    name: 'Matcha Croissant',
    hasSizes: false,
    price: 55000,
    stock: 3,
    row: 3,
    col: 1,
  },
  {
    id: 'almond_croissant_vn',
    categoryId: 'food',
    name: 'Almond Croissant VN',
    hasSizes: false,
    price: 55000,
    stock: 2,
    row: 3,
    col: 2,
  },
  {
    id: 'cream_custard_plait',
    categoryId: 'food',
    name: 'Cream Custard Plait',
    hasSizes: false,
    price: 55000,
    stock: 3,
    row: 3,
    col: 3,
    variant: 'item-yellow',
  },
];
