import type { MenuItem } from '@/types/pos';

// Subcategory: DESSERTS HN
export const FOOD_DESSERTS_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'cherry_cheesecake',
    categoryId: 'food',
    name: 'Cherry Cheesecake',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 1,
    col: 1,
  },
  {
    id: 'apple_cake',
    categoryId: 'food',
    name: 'Apple Cake',
    hasSizes: false,
    price: 60000,
    stock: 1,
    row: 1,
    col: 2,
  },
  {
    id: 'chocolate_coconut_ca',
    categoryId: 'food',
    name: 'Chocolate Coconut Ca',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 1,
    col: 3,
  },
  {
    id: 'mon_strawberry_yogurt',
    categoryId: 'food',
    name: 'Mon Strawberry Yogur',
    hasSizes: false,
    price: 55000,
    stock: 3,
    row: 1,
    col: 4,
  },
  {
    id: 'black_forest_cake',
    categoryId: 'food',
    name: 'Black Forest Cake',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'tiramisu',
    categoryId: 'food',
    name: 'Tiramisu',
    hasSizes: false,
    price: 65000,
    stock: 3,
    row: 2,
    col: 1,
  },
  {
    id: 'coconut_latte_mille',
    categoryId: 'food',
    name: 'Coconut Latte Mille',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 2,
    col: 2,
  },
  {
    id: 'astro_bliss_macaron',
    categoryId: 'food',
    name: 'Astro Bliss Macaron',
    hasSizes: false,
    price: 45000,
    stock: 2,
    row: 2,
    col: 3,
  },
  {
    id: 'mango_cheesecake',
    categoryId: 'food',
    name: 'Mango Cheesecake',
    hasSizes: false,
    price: 65000,
    stock: 1,
    row: 2,
    col: 4,
  },
  {
    id: 'straw_soft_cheesecak',
    categoryId: 'food',
    name: 'Straw Soft cheesecak',
    hasSizes: false,
    price: 65000,
    stock: 3,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'lemon_cheese_cake',
    categoryId: 'food',
    name: 'Lemon Cheese Cake',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 3,
    col: 1,
  },
  {
    id: 'grapefruit_mousse',
    categoryId: 'food',
    name: 'Grapefruit Mousse',
    hasSizes: false,
    price: 65000,
    stock: 1,
    row: 3,
    col: 2,
  },
  {
    id: 'egg_coffee_cake',
    categoryId: 'food',
    name: 'Egg Coffee Cake',
    hasSizes: false,
    price: 65000,
    stock: 3,
    row: 3,
    col: 3,
  },
  {
    id: 'matcha_creme',
    categoryId: 'food',
    name: 'Matcha Creme',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 3,
    col: 4,
  },
];

// Subcategory: SANDWICHES HN
export const FOOD_SANDWICHES_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'be_sandwich',
    categoryId: 'food',
    name: 'BE Sandwich',
    hasSizes: false,
    price: 60000,
    stock: 2,
    row: 1,
    col: 1,
  },
  {
    id: 'honey_ham_bagel',
    categoryId: 'food',
    name: 'Honey Ham Bagel',
    hasSizes: false,
    price: 65000,
    stock: 1,
    row: 1,
    col: 2,
  },
  {
    id: 'chicken_apple_sandw',
    categoryId: 'food',
    name: 'Chicken Apple Sandw',
    hasSizes: false,
    price: 65000,
    stock: 3,
    row: 1,
    col: 3,
  },
  {
    id: 'ham_cheese_croissa',
    categoryId: 'food',
    name: 'Ham_Cheese Croissa',
    hasSizes: false,
    price: 60000,
    stock: 5,
    row: 1,
    col: 4,
  },
  {
    id: 'floss_croffle',
    categoryId: 'food',
    name: 'Floss Croffle',
    hasSizes: false,
    price: 55000,
    stock: 3,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'mon_bacon_cheese_e',
    categoryId: 'food',
    name: 'Mon Bacon_Cheese_E',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 2,
    col: 1,
  },
  {
    id: 'mon_ham_cheese_pan',
    categoryId: 'food',
    name: 'Mon Ham_Cheese Pan',
    hasSizes: false,
    price: 65000,
    stock: 6,
    row: 2,
    col: 2,
  },
  {
    id: 'chicken_fajitas_pani',
    categoryId: 'food',
    name: 'Chicken Fajitas Pani',
    hasSizes: false,
    price: 70000,
    stock: 2,
    row: 2,
    col: 3,
  },
  {
    id: 'pulled_pork_cheese',
    categoryId: 'food',
    name: 'Pulled Pork Cheese',
    hasSizes: false,
    price: 70000,
    stock: 1,
    row: 2,
    col: 4,
  },
  {
    id: 'pesto_tomato_pasta',
    categoryId: 'food',
    name: 'Pesto Tomato Pasta',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'mushroom_empanadas',
    categoryId: 'food',
    name: 'Mushroom Empanadas',
    hasSizes: false,
    price: 55000,
    stock: 3,
    row: 3,
    col: 1,
  },
  {
    id: 'sweet_potato_chips',
    categoryId: 'food',
    name: 'Sweet Potato Chips',
    hasSizes: false,
    price: 35000,
    stock: 2,
    row: 3,
    col: 2,
  },
  {
    id: 'salmon_croissant',
    categoryId: 'food',
    name: 'Salmon Croissant',
    hasSizes: false,
    price: 70000,
    stock: 1,
    row: 3,
    col: 3,
  },
  {
    id: 'chicken_salad',
    categoryId: 'food',
    name: 'Chicken Salad',
    hasSizes: false,
    price: 65000,
    stock: 3,
    row: 3,
    col: 4,
  },
  {
    id: 'cheese_garlic_bun',
    categoryId: 'food',
    name: 'Cheese Garlic Bun',
    hasSizes: false,
    price: 50000,
    stock: 7,
    row: 3,
    col: 5,
  },

  // Row 4
  {
    id: 'pork_loaf_sandwich',
    categoryId: 'food',
    name: 'Pork Loaf Sandwich',
    hasSizes: false,
    price: 65000,
    stock: 2,
    row: 4,
    col: 1,
  },
  {
    id: 'satay_mushroom_sand',
    categoryId: 'food',
    name: 'Satay Mushroom Sand',
    hasSizes: false,
    price: 65000,
    stock: 1,
    row: 4,
    col: 2,
  },
  {
    id: 'coco_pork_sw',
    categoryId: 'food',
    name: 'Coco Pork SW',
    hasSizes: false,
    price: 70000,
    stock: 2,
    row: 4,
    col: 3,
  },
  {
    id: 'pepper_chicken_sw',
    categoryId: 'food',
    name: 'Pepper Chicken SW',
    hasSizes: false,
    price: 70000,
    stock: 1,
    row: 4,
    col: 4,
  },
];
