import type { MenuItem } from '@/types/pos';

export const DELIVERY_ITEMS: MenuItem[] = [
  {
    id: 'deli_wb_no_count',
    categoryId: 'delivery_item',
    name: 'Deli WB (NO COUNT)',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 1,
  },
  {
    id: 'deli_merch',
    categoryId: 'delivery_item',
    name: 'Deli Merch',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 2,
  },
];

export const SBUX_CARD_ITEMS: MenuItem[] = [
  {
    id: 'starbucks_card',
    categoryId: 'sbux_card',
    name: 'Starbucks Card',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 1,
  },
];

export const SBAPP_MERCHANDISE_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'sbapp_800110444_sr_reuse_c',
    categoryId: 'sbapp_merchandise',
    name: '800110444 SR REUSE C',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 1,
  },
  {
    id: 'sbapp_fy26win_coffee_craft',
    categoryId: 'sbapp_merchandise',
    name: 'FY26WIN-COFFEE CRAFT',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 2,
  },
  {
    id: 'sbapp_fy26spr_harry_potter',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SPR-HARRY POTTER',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 3,
  },
  {
    id: 'sbapp_fy26sum1_bear_resort',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM1-BEAR RESORT',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 4,
  },
  {
    id: 'sbapp_fy26sum1_bear_journe',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM1-BEAR JOURNE',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'sbapp_fy26sum1_wireframe',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM1-WIREFRAME',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 1,
  },
  {
    id: 'sbapp_fy26sum_horoscope',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM-HOROSCOPE',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 2,
  },
  {
    id: 'sbapp_sum2_easy_breezy',
    categoryId: 'sbapp_merchandise',
    name: 'SUM2-EASY BREEZY',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 3,
  },
  {
    id: 'sbapp_sum2_rainbow',
    categoryId: 'sbapp_merchandise',
    name: 'SUM2-RAINBOW',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 4,
  },
  {
    id: 'sbapp_fy26sum3_whimsy',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM3-WHIMSY',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'sbapp_fy26sum3_taste_sum',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM3-TASTE SUM',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 1,
  },
  {
    id: 'sbapp_fy26sum3_bunny_feast',
    categoryId: 'sbapp_merchandise',
    name: 'FY26SUM3-BUNNY FEAST',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 2,
  },
  {
    id: 'sbapp_fy27aut_siren_muse',
    categoryId: 'sbapp_merchandise',
    name: 'FY27AUT-SIREN MUSE',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 3,
  },
  {
    id: 'sbapp_fy27aut_peanuts',
    categoryId: 'sbapp_merchandise',
    name: 'FY27AUT-PEANUTS',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 4,
  },
  {
    id: 'sbapp_fy27aut_dark_roast',
    categoryId: 'sbapp_merchandise',
    name: 'FY27AUT-DARK ROAST',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 5,
  },

  // Row 4
  {
    id: 'sbapp_fy27aut_meowchestra',
    categoryId: 'sbapp_merchandise',
    name: 'FY27AUT-MEOWCHESTRA',
    hasSizes: false,
    price: 0,
    row: 4,
    col: 1,
  },
  {
    id: 'sbapp_fy27aut_winnie_pooh',
    categoryId: 'sbapp_merchandise',
    name: 'FY27AUT-WINNIE POOH',
    hasSizes: false,
    price: 0,
    row: 4,
    col: 2,
  },
];
