import type { MenuItem } from '@/types/pos';

export const NSO_PROMO_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'nso_sr_enamel_pin',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: 'NSO - SR_Enamel Pin',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 1,
  },
  {
    id: 'nso_sr_reusable_cu',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: 'NSO - SR_Reusable Cu',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 2,
  },
  {
    id: 'nso_0800110574_sr_gwp_ns',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '0800110574 SR GWP NS',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 3,
  },
  {
    id: 'nso_800110464_rpet_reusa',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110464 RPET Reusa',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 4,
  },
  {
    id: 'nso_800110444_sr_reuse_c',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110444 SR REUSE C',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'nso_800110445_sr_reuse_c',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110445 SR REUSE C',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 1,
  },
  {
    id: 'nso_800110724_sr_gwp_nso',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110724 SR GWP NSO',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 2,
  },
  {
    id: 'nso_800110725_sr_gwp_nso',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110725 SR GWP NSO',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 3,
  },
  {
    id: 'nso_800110767_sr_gwp_nso',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110767 SR GWP NSO',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 4,
  },
  {
    id: 'nso_800110768_sr_gwp_nso',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110768 SR GWP NSO',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'nso_pin_tet_bearista',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: 'Pin Tet Bearista',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 1,
  },
  {
    id: 'nso_800110835_sr_gwp_nso',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '800110835 SR GWP? NSO',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 2,
  },
  {
    id: 'nso_17026_nso_gwp',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '17026 NSO GWP',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 3,
  },
  {
    id: 'nso_17020_nso_gwp',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '17020 NSO GWP',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 4,
  },
  {
    id: 'nso_17023_nso_gwp',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '17023 NSO GWP',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 5,
  },

  // Row 4
  {
    id: 'nso_17015_nso_gwp',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '17015 NSO GWP',
    hasSizes: false,
    price: 0,
    row: 4,
    col: 1,
  },
  {
    id: 'nso_16476_nso_gwp',
    categoryId: 'discount',
    subcategoryId: 'nso_promo',
    name: '16476 NSO GWP',
    hasSizes: false,
    price: 0,
    row: 4,
    col: 2,
  },
];
