import type { MenuItem } from '@/types/pos';

// PK HN category items
export const PK_HN_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'oatmeal_cookie',
    categoryId: 'pk_hn',
    name: 'Oatmeal Cookie',
    hasSizes: false,
    price: 35000,
    row: 1,
    col: 1,
  },
  {
    id: 'mixed_berry_crispy_c',
    categoryId: 'pk_hn',
    name: 'Mixed Berry Crispy C',
    hasSizes: false,
    price: 35000,
    row: 1,
    col: 2,
  },
  {
    id: 'cocoa_cereal_crispy',
    categoryId: 'pk_hn',
    name: 'Cocoa cereal crispy',
    hasSizes: false,
    price: 35000,
    row: 1,
    col: 3,
  },
  {
    id: 'keo_classic_mints_pe',
    categoryId: 'pk_hn',
    name: 'Keo Classic mints pe',
    hasSizes: false,
    price: 45000,
    row: 1,
    col: 4,
  },
  {
    id: 'keo_classic_mints_pe_2',
    categoryId: 'pk_hn',
    name: 'Keo Classic mints Pe',
    hasSizes: false,
    price: 45000,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'mixed_nuts_bar',
    categoryId: 'pk_hn',
    name: 'Mixed Nuts Bar',
    hasSizes: false,
    price: 40000,
    row: 2,
    col: 1,
  },
  {
    id: 'cornflakes_honey_car',
    categoryId: 'pk_hn',
    name: 'Cornflakes Honey Car',
    hasSizes: false,
    price: 40000,
    row: 2,
    col: 2,
  },
  {
    id: 'cookie_cream_choco',
    categoryId: 'pk_hn',
    name: 'Cookie Cream Choco',
    hasSizes: false,
    price: 40000,
    row: 2,
    col: 3,
  },
  {
    id: 'bunny_chocolate',
    categoryId: 'pk_hn',
    name: 'Bunny Chocolate',
    hasSizes: false,
    price: 45000,
    row: 2,
    col: 4,
  },
  {
    id: 'barista_cookie',
    categoryId: 'pk_hn',
    name: 'Barista Cookie',
    hasSizes: false,
    price: 40000,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'choco_chips_cookie',
    categoryId: 'pk_hn',
    name: 'Choco Chips Cookie',
    hasSizes: false,
    price: 40000,
    row: 3,
    col: 1,
  },
  {
    id: '800110438_lollypops',
    categoryId: 'pk_hn',
    name: '800110438 LOLLYPOPS',
    hasSizes: false,
    price: 25000,
    row: 3,
    col: 2,
  },
  {
    id: 'box_4pcspre_mooncake',
    categoryId: 'pk_hn',
    name: 'Box 4PCSPre Mooncake',
    hasSizes: false,
    price: 580000,
    row: 3,
    col: 3,
  },
  {
    id: 'box_4pcs_mooncake',
    categoryId: 'pk_hn',
    name: 'Box 4PCS Mooncake',
    hasSizes: false,
    price: 580000,
    row: 3,
    col: 4,
  },
  {
    id: 'box_2pcs_mooncake',
    categoryId: 'pk_hn',
    name: 'Box 2PCS Mooncake',
    hasSizes: false,
    price: 320000,
    row: 3,
    col: 5,
  },

  // Row 4
  {
    id: 'sea_salt_espresso_mc',
    categoryId: 'pk_hn',
    name: 'Sea Salt Espresso MC',
    hasSizes: false,
    price: 130000,
    row: 4,
    col: 1,
  },
  {
    id: 'lava_cheese_mc',
    categoryId: 'pk_hn',
    name: 'Lava Cheese MC',
    hasSizes: false,
    price: 130000,
    row: 4,
    col: 2,
  },
  {
    id: '800110824_mon_banh_t',
    categoryId: 'pk_hn',
    name: '800110824 Mon Banh T',
    hasSizes: false,
    price: 130000,
    row: 4,
    col: 3,
  },
];

// PACKAGING category items
export const PACKAGING_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'gift_set_single_bag',
    categoryId: 'packaging',
    name: 'GIFT SET SINGLE BAG',
    hasSizes: false,
    price: 15000,
    row: 1,
    col: 1,
  },
  {
    id: 'gift_set_double_bag',
    categoryId: 'packaging',
    name: 'GIFT SET DOUBLE BAG',
    hasSizes: false,
    price: 25000,
    row: 1,
    col: 2,
  },
  {
    id: 'card_box_medium_bag',
    categoryId: 'packaging',
    name: 'CARD BOX MEDIUM BAG',
    hasSizes: false,
    price: 20000,
    row: 1,
    col: 3,
  },
  {
    id: 'paper_bag',
    categoryId: 'packaging',
    name: 'Paper Bag',
    hasSizes: false,
    price: 5000,
    row: 1,
    col: 4,
  },
  {
    id: 'plastic_bag',
    categoryId: 'packaging',
    name: 'Plastic bag',
    hasSizes: false,
    price: 3000,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'pvc_plastic_bag',
    categoryId: 'packaging',
    name: 'PVC PLASTIC BAG',
    hasSizes: false,
    price: 25000,
    row: 2,
    col: 1,
  },
  {
    id: 'molly_500d_bag_1',
    categoryId: 'packaging',
    name: 'MOLLY 500d - BAG - I',
    hasSizes: false,
    price: 45000,
    row: 2,
    col: 2,
  },
];

// DISCOUNT category items
export const DISCOUNT_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'personal_cup',
    categoryId: 'discount',
    name: 'Personal Cup',
    hasSizes: false,
    price: -10000,
    row: 1,
    col: 1,
  },
  {
    id: 'parking_10k',
    categoryId: 'discount',
    name: 'Parking 10k',
    hasSizes: false,
    price: -10000,
    row: 1,
    col: 2,
  },
  {
    id: 'parking_5k',
    categoryId: 'discount',
    name: 'Parking 5k',
    hasSizes: false,
    price: -5000,
    row: 1,
    col: 3,
  },
  {
    id: 'jcr_discount',
    categoryId: 'discount',
    name: 'JCR Discount',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 4,
  },
  {
    id: 'shake_shack_discount',
    categoryId: 'discount',
    name: 'Shake Shack Discount',
    hasSizes: false,
    price: 0,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'lsm_promo',
    categoryId: 'discount',
    name: 'LSM Promo',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 1,
  },
  {
    id: 'nso_promo',
    categoryId: 'discount',
    name: 'NSO Promo',
    isSubcategory: true,
    hasSizes: false,
    price: 0,
    row: 2,
    col: 2,
  },
  {
    id: 'b2b_discount',
    categoryId: 'discount',
    name: 'B2B Discount',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 3,
  },
  {
    id: 'b2b_package',
    categoryId: 'discount',
    name: 'B2B Package',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 4,
  },
  {
    id: 'int_visa_bin',
    categoryId: 'discount',
    name: 'Int VISA BIN',
    hasSizes: false,
    price: 0,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'fy26sum2_gwp',
    categoryId: 'discount',
    name: 'FY26Sum2 GWP',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 1,
  },
  {
    id: 'fy26sum3_gwp',
    categoryId: 'discount',
    name: 'FY26Sum3 GWP',
    hasSizes: false,
    price: 0,
    row: 3,
    col: 2,
  },
];
