import type { MenuItem } from '@/types/pos';

// Top-level TEA menu (subcategories)
export const TEA_ITEMS: MenuItem[] = [
  // Row 1
  {
    id: 'tea_ds_black_tea',
    categoryId: 'tea',
    name: 'DS BLACK TEA',
    isSubcategory: true,
    row: 1,
    col: 1,
  },
  {
    id: 'tea_ds_green_tea',
    categoryId: 'tea',
    name: 'DS GREEN TEA',
    isSubcategory: true,
    row: 1,
    col: 2,
  },
  {
    id: 'tea_ds_hibiscus',
    categoryId: 'tea',
    name: 'DS HIBISCUS',
    isSubcategory: true,
    row: 1,
    col: 3,
  },
  {
    id: 'tea_tea_latte',
    categoryId: 'tea',
    name: 'TEA LATTE',
    isSubcategory: true,
    row: 1,
    col: 4,
  },
  {
    id: 'tea_eng_breakfast',
    categoryId: 'tea',
    name: 'ENG BREAKFAST',
    isSubcategory: true,
    row: 1,
    col: 5,
  },

  // Row 2
  {
    id: 'tea_earl_grey',
    categoryId: 'tea',
    name: 'EARL GREY',
    isSubcategory: true,
    row: 2,
    col: 1,
  },
  {
    id: 'tea_emp',
    categoryId: 'tea',
    name: 'EMP',
    isSubcategory: true,
    row: 2,
    col: 2,
  },
  {
    id: 'tea_mint_citrus',
    categoryId: 'tea',
    name: 'MINT CITRUS',
    isSubcategory: true,
    row: 2,
    col: 3,
  },
  {
    id: 'tea_hibicus',
    categoryId: 'tea',
    name: 'HIBICUS',
    isSubcategory: true,
    row: 2,
    col: 4,
  },
  {
    id: 'tea_chamomile',
    categoryId: 'tea',
    name: 'CHAMOMILE',
    isSubcategory: true,
    row: 2,
    col: 5,
  },

  // Row 3
  {
    id: 'tea_zen_oolong_tea',
    categoryId: 'tea',
    name: 'Zen Oolong Tea',
    isSubcategory: true,
    row: 3,
    col: 1,
  },
];

// Subcategory: DS BLACK TEA
export const TEA_DS_BLACK_TEA_ITEMS: MenuItem[] = [
  {
    id: 't_bt',
    categoryId: 'tea',
    name: 'T BT',
    baseName: 'BT',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 1,
    col: 1,
  },
  {
    id: 't_btl',
    categoryId: 'tea',
    name: 'T BTL',
    baseName: 'BTL',
    hasSizes: true,
    price: 70000,
    prices: { S: 65000, T: 70000, G: 80000, V: 90000 },
    row: 1,
    col: 2,
  },
  {
    id: 't_iced_black_tea',
    categoryId: 'tea',
    name: 'T Iced BLACK Tea',
    baseName: 'Iced BLACK Tea',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 1,
    col: 3,
  },
  {
    id: 'b_iced_bt_mbro',
    categoryId: 'tea',
    name: 'B Iced BT AMBRO',
    baseName: 'Iced BT AMBRO',
    hasSizes: false,
    price: 75000,
    soldOut: true,
    row: 1,
    col: 4,
  },
  {
    id: 't_btg',
    categoryId: 'tea',
    name: 'T BTG',
    baseName: 'BTG',
    hasSizes: true,
    price: 70000,
    prices: { S: 65000, T: 70000, G: 80000, V: 90000 },
    row: 1,
    col: 5,
  },
  {
    id: 't_iced_btg',
    categoryId: 'tea',
    name: 'T Iced BTG',
    baseName: 'Iced BTG',
    hasSizes: true,
    price: 70000,
    prices: { S: 65000, T: 70000, G: 80000, V: 90000 },
    row: 2,
    col: 1,
  },
];

// Subcategory: DS GREEN TEA
export const TEA_DS_GREEN_TEA_ITEMS: MenuItem[] = [
  {
    id: 't_gt',
    categoryId: 'tea',
    name: 'T GT',
    baseName: 'GT',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 1,
    col: 1,
  },
  {
    id: 't_gtl',
    categoryId: 'tea',
    name: 'T GTL',
    baseName: 'GTL',
    hasSizes: true,
    price: 70000,
    prices: { S: 65000, T: 70000, G: 80000, V: 90000 },
    row: 1,
    col: 2,
  },
  {
    id: 't_iced_gt',
    categoryId: 'tea',
    name: 'T Iced GT',
    baseName: 'Iced GT',
    hasSizes: true,
    price: 60000,
    prices: { S: 55000, T: 60000, G: 70000, V: 80000 },
    row: 1,
    col: 3,
  },
  {
    id: 't_sgtl',
    categoryId: 'tea',
    name: 'T SGTL',
    baseName: 'SGTL',
    hasSizes: true,
    price: 75000,
    prices: { S: 70000, T: 75000, G: 85000, V: 95000 },
    row: 1,
    col: 4,
  },
  {
    id: 'b_iced_gt_ambro',
    categoryId: 'tea',
    name: 'B Iced GT AMBRO',
    baseName: 'Iced GT AMBRO',
    hasSizes: false,
    price: 75000,
    soldOut: true,
    row: 1,
    col: 5,
  },
];
